name: Deployment (Container)

on:
  push:
    branches:
      - master
      - dev

env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo

jobs:
  test:
    name: Test App
    environment: testing
    runs-on: ubuntu-latest
    container:
      image: node:16
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb+srv
      MONGODB_CLUSTER_ADDRESS: cluster0.ntrwp.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Start server and wait
        run: npm start & npx wait-on http://127.0.0.1:$PORT

      - name: Run tests
        run: npm test

      - name: Output information (no secrets)
        run: |
          echo "Connected to DB: $MONGODB_CLUSTER_ADDRESS"
          echo "DB name: $MONGODB_DB_NAME"

  deploy:
    name: Deploy App
    needs: test
    runs-on: ubuntu-latest
    env:
      PORT: 3000
    steps:
      - name: Output deployment info
        run: |
          echo "Deploying app..."
          echo "DB: $MONGODB_DB_NAME"
          echo "PORT: $PORT"
